import {Clock, Console, Crypto, DateTime, Effect, FileSystem, Option, Path, Schema} from 'effect';
import * as yaml from 'js-yaml';
import {sha256Hex} from '@threadnote/platform/digest';
import {withExclusiveFileLock} from '@threadnote/platform/file/lock';
import {ResourceStore} from '@threadnote/store/resource-store';
import {uriSegment} from '@threadnote/workspace/manifest';
import {formatMemoryCodeCitation} from '@threadnote/memory/code/citation';
import {
  canonicalMemoryDocumentContent,
  isSharedMemoryUri,
  parseMemoryDocument,
  type MemoryRecord,
  type MemoryRelation,
} from '@threadnote/memory/document';
import {
  type ObsidianProjectionConfig,
  isObsidianSource,
  mutateSourceConfiguration,
  readObsidianConfiguration,
  removeObsidianProjection,
  requireObsidianProjection,
  upsertObsidianProjection,
} from './config.js';
import {applyScrubber} from '@threadnote/platform/scrubber';
import {parseResourceId, resourceIdWithoutAnchor} from '@threadnote/store/resource-id';
import type {MemoryKind, MemoryStatus} from '@threadnote/memory/types';
import type {RuntimeConfig} from '@threadnote/workspace/config';
import {expandPath} from '@threadnote/platform/paths';
import {isDirectory, toPosixPath} from '../utils.js';

class ObsidianProjectionError extends Schema.TaggedError<ObsidianProjectionError>()('ObsidianProjectionError', {
  cause: Schema.optionalKey(Schema.Defect()),
  message: Schema.String,
}) {}

export interface ObsidianProjectionAddOptions {
  /** Omit to preserve selection; null explicitly selects all matching memories. */
  readonly selectedUris?: readonly string[] | null;
  readonly apply?: boolean;
  readonly folder: string;
  readonly id: string;
  readonly includeShared?: boolean;
  readonly kinds?: readonly MemoryKind[];
  readonly statuses?: readonly MemoryStatus[];
  readonly vault: string;
}

export interface ObsidianProjectionCommandOptions {
  readonly apply?: boolean;
  readonly dryRun?: boolean;
  readonly force?: boolean;
  readonly id: string;
}

export interface ObsidianProjectionPublishOptions extends ObsidianProjectionCommandOptions {
  readonly uris: readonly string[];
}

export type ObsidianProjectionAction = 'add' | 'drift' | 'remove' | 'skip' | 'unchanged' | 'update';

export interface ObsidianProjectionEntry {
  readonly action: ObsidianProjectionAction;
  readonly detail?: string;
  readonly relativePath: string;
  readonly uri?: string;
}

interface ObsidianProjectionFileState {
  readonly contentHash: string;
  readonly uri?: string;
}

export interface ObsidianProjectionState {
  readonly files: Readonly<Record<string, ObsidianProjectionFileState>>;
  readonly projectionId: string;
  readonly syncedAt?: string;
  readonly version: 1;
}

interface DesiredProjectionFile {
  readonly content: string;
  readonly contentHash: string;
  readonly relativePath: string;
  readonly uri?: string;
}

interface ProjectionPlan {
  readonly desired: ReadonlyMap<string, DesiredProjectionFile>;
  readonly entries: readonly ObsidianProjectionEntry[];
  readonly projection: ObsidianProjectionConfig;
  readonly state: ObsidianProjectionState;
}

const PROJECTION_STATE_VERSION = 1;
const PROJECTION_STATE_FILENAME = '.threadnote-projection-v1.json';
const PROJECTION_MANAGED_MARKER = 'Generated by threadnote projection';
const PROJECTION_PRIVATE_FILE_MODE = 0o600;
const PROJECTION_NOTE_FILE_MODE = 0o644;
const PROJECTION_LOCK_RETRY_MILLISECONDS = 25;
const PROJECTION_LOCK_STALE_MILLISECONDS = 5 * 60 * 1_000;
const PROJECTION_LOCK_WAIT_MILLISECONDS = 10_000;
const PROJECTION_LOCK_OPTIONS = {
  retryIntervalMilliseconds: PROJECTION_LOCK_RETRY_MILLISECONDS,
  staleAfterMilliseconds: PROJECTION_LOCK_STALE_MILLISECONDS,
  waitTimeoutMilliseconds: PROJECTION_LOCK_WAIT_MILLISECONDS,
} as const;
const PROJECTION_WRITE_CONCURRENCY = 8;
const MEMORY_READ_CONCURRENCY = 16;

export const runObsidianProjectionAdd = Effect.fn('obsidian.projectionAdd')(function* (
  config: RuntimeConfig,
  options: ObsidianProjectionAddOptions,
) {
  const id = normalizeIdentifier(options.id, 'projection id');
  const vault = yield* canonicalDirectory(options.vault, 'Obsidian vault');
  const folder = normalizeProjectionFolder(options.folder);
  const current = yield* readObsidianConfiguration(config);
  const existing = current.projections.find(projection => projection.id === id);
  const projection: ObsidianProjectionConfig = {
    enabled: existing?.enabled ?? true,
    folder,
    id,
    includeShared: options.includeShared !== false,
    kinds: options.kinds?.length ? [...new Set(options.kinds)] : ['durable', 'handoff'],
    selectedUris:
      options.selectedUris === null
        ? undefined
        : options.selectedUris !== undefined
          ? normalizeProjectionMemoryUris(config, options.selectedUris)
          : existing
            ? existing.selectedUris
            : [],
    statuses: options.statuses?.length ? [...new Set(options.statuses)] : ['active'],
    type: 'obsidian',
    vault,
  };
  const projectionExclude = `${folder}/**`;
  const withProjection = (configuration: typeof current) => {
    const sources = configuration.sources.map(source =>
      isObsidianSource(source) && source.vault === vault && !source.exclude.includes(projectionExclude)
        ? {...source, exclude: [...source.exclude, projectionExclude]}
        : source,
    );
    const next =
      configuration.version === 1
        ? {version: 1 as const, sources: sources.filter(isObsidianSource), projections: configuration.projections}
        : {version: 2 as const, sources, projections: configuration.projections};
    const latest = configuration.projections.find(item => item.id === id);
    return upsertObsidianProjection(next, {
      ...projection,
      enabled: latest?.enabled ?? true,
      selectedUris: options.selectedUris !== undefined ? projection.selectedUris : latest ? latest.selectedUris : [],
    });
  };
  const sources = withProjection(current).sources;
  if (options.apply !== true) {
    yield* Console.log(`Would configure Obsidian projection "${id}":`);
    yield* Console.log(projectionSummary(projection));
    if (sources.some((source, index) => source !== current.sources[index])) {
      yield* Console.log(`Would exclude ${projectionExclude} from matching sources in the same vault.`);
    }
    yield* Console.log('Re-run with --apply to write the configuration.');
    return;
  }
  const path = yield* mutateSourceConfiguration(config, withProjection);
  yield* Console.log(`Configured Obsidian projection "${id}" in ${path}.`);
});

export const runObsidianProjectionList = Effect.fn('obsidian.projectionList')(function* (config: RuntimeConfig) {
  const configuration = yield* readObsidianConfiguration(config);
  if (configuration.projections.length === 0) {
    yield* Console.log('No Obsidian projections configured.');
    return;
  }
  for (const projection of configuration.projections) {
    yield* Console.log(projectionSummary(projection));
  }
});

export const runObsidianProjectionStatus = Effect.fn('obsidian.projectionStatus')(function* (
  config: RuntimeConfig,
  id: string,
) {
  const projection = requireObsidianProjection(yield* readObsidianConfiguration(config), id);
  const plan = yield* buildProjectionPlan(config, projection);
  const counts = projectionCounts(plan.entries);
  yield* Console.log(projectionSummary(projection));
  yield* Console.log(
    `State: ${counts.unchanged} current, ${counts.add} add, ${counts.update} update, ` +
      `${counts.remove} remove, ${counts.drift} drift, ${counts.skip} skipped.`,
  );
});

export const runObsidianProjectionSync = Effect.fn('obsidian.projectionSync')(function* (
  config: RuntimeConfig,
  options: ObsidianProjectionCommandOptions,
) {
  const apply = options.apply === true && options.dryRun !== true;
  const projection = requireObsidianProjection(yield* readObsidianConfiguration(config), options.id);
  if (!projection.enabled) {
    return yield* ObsidianProjectionError.make({message: `Obsidian projection "${projection.id}" is disabled.`});
  }
  const fs = yield* FileSystem.FileSystem;
  const root = yield* projectionRoot(projection);
  const statePath = yield* projectionStatePath(projection);
  return yield* withExclusiveFileLock(
    fs,
    `${statePath}.lock`,
    PROJECTION_LOCK_OPTIONS,
    Effect.gen(function* () {
      const plan = yield* buildProjectionPlan(config, projection);
      yield* printProjectionPlan(plan);
      if (!apply) {
        yield* Console.log('Dry run complete. Re-run with --apply to update the projection.');
        return plan.entries;
      }
      const nextFiles: Record<string, ObsidianProjectionFileState> = {...plan.state.files};
      const mutableEntries = [...plan.entries];
      const writes = mutableEntries.filter(
        entry =>
          entry.action === 'add' ||
          entry.action === 'update' ||
          (entry.action === 'drift' && options.force === true && plan.desired.has(entry.relativePath)),
      );
      yield* Effect.forEach(
        writes,
        entry =>
          Effect.gen(function* () {
            const desired = plan.desired.get(entry.relativePath);
            if (!desired) {
              return;
            }
            yield* writeProjectionFile(root, desired);
            nextFiles[entry.relativePath] = {contentHash: desired.contentHash, uri: desired.uri};
          }),
        {concurrency: PROJECTION_WRITE_CONCURRENCY, discard: true},
      );
      for (const entry of mutableEntries.filter(item => item.action === 'unchanged')) {
        const desired = plan.desired.get(entry.relativePath);
        if (desired) {
          nextFiles[entry.relativePath] = {contentHash: desired.contentHash, uri: desired.uri};
        }
      }
      const removals = mutableEntries.filter(
        entry =>
          entry.action === 'remove' ||
          (entry.action === 'drift' && options.force === true && !plan.desired.has(entry.relativePath)),
      );
      for (const entry of removals) {
        const target = yield* safeProjectionTarget(root, entry.relativePath);
        yield* fs.remove(target, {force: true});
        delete nextFiles[entry.relativePath];
      }
      const currentTimeMillis = yield* Clock.currentTimeMillis;
      const nextState: ObsidianProjectionState = {
        files: nextFiles,
        projectionId: projection.id,
        syncedAt: DateTime.formatIso(DateTime.makeUnsafe(currentTimeMillis)),
        version: PROJECTION_STATE_VERSION,
      };
      yield* writeProjectionState(statePath, nextState);
      const counts = projectionCounts(mutableEntries);
      yield* Console.log(
        `Projection sync complete: ${counts.add} added, ${counts.update} updated, ${counts.remove} removed, ` +
          `${counts.unchanged} unchanged, ${counts.drift} drift, ${counts.skip} skipped.`,
      );
      return mutableEntries;
    }),
  );
});

export const runObsidianProjectionPublish = Effect.fn('obsidian.projectionPublish')(function* (
  config: RuntimeConfig,
  options: ObsidianProjectionPublishOptions,
) {
  const apply = options.apply === true && options.dryRun !== true;
  const configuration = yield* readObsidianConfiguration(config);
  const projection = requireObsidianProjection(configuration, options.id);
  if (!projection.enabled) {
    return yield* ObsidianProjectionError.make({message: `Obsidian projection "${projection.id}" is disabled.`});
  }
  if (projection.selectedUris === undefined) {
    return yield* ObsidianProjectionError.make({
      message:
        `Obsidian projection "${projection.id}" predates explicit memory selection. ` +
        'Re-run threadnote projection add with the same id, vault, and folder plus --apply, then publish again.',
    });
  }
  const requestedUris = normalizeProjectionMemoryUris(config, options.uris);
  const selectedUris = [...new Set([...projection.selectedUris, ...requestedUris])].sort((left, right) =>
    left.localeCompare(right),
  );
  const nextProjection = {...projection, selectedUris};
  const plan = yield* buildProjectionPlan(config, nextProjection);
  const projectedUris = new Set([...plan.desired.values()].flatMap(file => (file.uri === undefined ? [] : [file.uri])));
  const unavailable = requestedUris.filter(uri => !projectedUris.has(uri));
  if (unavailable.length > 0) {
    return yield* ObsidianProjectionError.make({
      message:
        `Cannot publish ${unavailable.join(', ')}. Ensure each memory exists and matches projection ` +
        `"${projection.id}" kind, status, and shared-memory filters.`,
    });
  }
  const addedSelectionCount = selectedUris.length - projection.selectedUris.length;
  yield* Console.log(
    `${apply ? 'Publishing' : 'Would publish'} ${requestedUris.length} selected memory URI(s) to ` +
      `Obsidian projection "${projection.id}" (${addedSelectionCount} newly selected).`,
  );
  if (!apply) {
    yield* printProjectionPlan(plan);
    yield* Console.log('Dry run complete. Re-run with --apply to write the selected memories to the vault.');
    return plan.entries;
  }
  yield* mutateSourceConfiguration(config, latest => {
    const currentProjection = requireObsidianProjection(latest, projection.id);
    const currentSelection = currentProjection.selectedUris ?? [];
    return upsertObsidianProjection(latest, {
      ...currentProjection,
      selectedUris: [...new Set([...currentSelection, ...requestedUris])].sort((left, right) =>
        left.localeCompare(right),
      ),
    });
  });
  return yield* runObsidianProjectionSync(config, {
    apply: true,
    force: options.force,
    id: projection.id,
  });
});

export const runObsidianProjectionRemove = Effect.fn('obsidian.projectionRemove')(function* (
  config: RuntimeConfig,
  options: ObsidianProjectionCommandOptions,
) {
  const apply = options.apply === true && options.dryRun !== true;
  const configuration = yield* readObsidianConfiguration(config);
  const projection = requireObsidianProjection(configuration, options.id);
  const plan = yield* buildProjectionPlan(config, projection, {empty: true});
  yield* printProjectionPlan(plan);
  const drift = plan.entries.filter(entry => entry.action === 'drift');
  if (!apply) {
    yield* Console.log('Would remove unchanged managed projection files and preserve the vault and memories.');
    yield* Console.log('Re-run with --apply to continue.');
    return;
  }
  if (drift.length > 0 && options.force !== true) {
    return yield* ObsidianProjectionError.make({
      message:
        `Projection "${projection.id}" contains ${drift.length} edited managed file(s). ` +
        'Resolve them or repeat with --force to remove the managed files.',
    });
  }
  const fs = yield* FileSystem.FileSystem;
  const root = yield* projectionRoot(projection);
  const statePath = yield* projectionStatePath(projection);
  yield* withExclusiveFileLock(
    fs,
    `${statePath}.lock`,
    PROJECTION_LOCK_OPTIONS,
    Effect.gen(function* () {
      for (const entry of plan.entries.filter(item => item.action === 'remove' || item.action === 'drift')) {
        yield* fs.remove(yield* safeProjectionTarget(root, entry.relativePath), {force: true});
      }
      yield* fs.remove(statePath, {force: true});
      yield* mutateSourceConfiguration(config, latest => removeObsidianProjection(latest, projection.id));
      yield* removeEmptyProjectionDirectories(root);
    }),
  );
  yield* Console.log(`Removed Obsidian projection "${projection.id}". The vault and memories were preserved.`);
});

export const resolveProjectedMemoryPath = Effect.fn('obsidian.resolveProjectedMemoryPath')(function* (
  config: RuntimeConfig,
  uri: string,
  projectionId?: string,
) {
  const configuration = yield* readObsidianConfiguration(config);
  const projections = configuration.projections.filter(
    projection => projection.enabled && (projectionId === undefined || projection.id === projectionId),
  );
  const matches: Array<{path: string; projection: ObsidianProjectionConfig; relativePath: string}> = [];
  for (const projection of projections) {
    const state = yield* readProjectionState(yield* projectionStatePath(projection), projection.id);
    for (const [relativePath, entry] of Object.entries(state.files)) {
      if (entry.uri === uri) {
        const root = yield* projectionRoot(projection);
        matches.push({
          path: yield* safeProjectionTarget(root, relativePath),
          projection,
          relativePath,
        });
      }
    }
  }
  if (matches.length === 0) {
    return yield* ObsidianProjectionError.make({
      message:
        `Memory ${uri} is not present in an enabled Obsidian projection. ` +
        'Run threadnote projection publish <id> --uri <memory-uri> --apply.',
    });
  }
  if (matches.length > 1) {
    return yield* ObsidianProjectionError.make({
      message: `Memory ${uri} appears in multiple projections. Pass --projection with one of: ${matches
        .map(match => match.projection.id)
        .join(', ')}.`,
    });
  }
  return matches[0];
});

const buildProjectionPlan = Effect.fn('obsidian.buildProjectionPlan')(function* (
  config: RuntimeConfig,
  projection: ObsidianProjectionConfig,
  options: {readonly empty?: boolean} = {},
) {
  const fs = yield* FileSystem.FileSystem;
  const root = yield* projectionRoot(projection);
  const state = yield* readProjectionState(yield* projectionStatePath(projection), projection.id);
  const records = options.empty === true ? [] : yield* readProjectionMemories(config, projection);
  const desired = options.empty === true ? new Map() : yield* desiredProjectionFiles(projection, records);
  const entries: ObsidianProjectionEntry[] = [];
  for (const [relativePath, file] of desired) {
    const target = yield* safeProjectionTarget(root, relativePath);
    const recorded = state.files[relativePath];
    const currentHash = yield* fileContentHash(fs, target);
    if (!recorded) {
      entries.push({
        action: currentHash === undefined ? 'add' : 'skip',
        detail: currentHash === undefined ? undefined : 'unmanaged file occupies the projected path',
        relativePath,
        uri: file.uri,
      });
      continue;
    }
    if (currentHash === undefined) {
      entries.push({action: 'add', detail: 'managed file is missing', relativePath, uri: file.uri});
    } else if (currentHash !== recorded.contentHash) {
      entries.push({action: 'drift', detail: 'managed file was edited', relativePath, uri: file.uri});
    } else if (currentHash === file.contentHash) {
      entries.push({action: 'unchanged', relativePath, uri: file.uri});
    } else {
      entries.push({action: 'update', relativePath, uri: file.uri});
    }
  }
  for (const [relativePath, recorded] of Object.entries(state.files)) {
    if (desired.has(relativePath)) {
      continue;
    }
    const target = yield* safeProjectionTarget(root, relativePath);
    const currentHash = yield* fileContentHash(fs, target);
    if (currentHash === undefined) {
      entries.push({action: 'remove', detail: 'state entry is already absent', relativePath, uri: recorded.uri});
    } else if (currentHash !== recorded.contentHash) {
      entries.push({action: 'drift', detail: 'orphaned managed file was edited', relativePath, uri: recorded.uri});
    } else {
      entries.push({action: 'remove', relativePath, uri: recorded.uri});
    }
  }
  entries.sort(
    (left, right) =>
      projectionActionRank(left.action) - projectionActionRank(right.action) ||
      left.relativePath.localeCompare(right.relativePath),
  );
  return {desired, entries, projection, state} satisfies ProjectionPlan;
});

const readProjectionMemories = Effect.fn('obsidian.readProjectionMemories')(function* (
  config: RuntimeConfig,
  projection: ObsidianProjectionConfig,
) {
  const store = yield* ResourceStore;
  const location = resourceStoreLocation(config);
  const selectedUris =
    projection.selectedUris ??
    (yield* store.list(location, `threadnote://user/${uriSegment(config.user)}/memories`, {recursive: true}).pipe(
      Effect.catchTag('ResourceNotFound', () => Effect.succeed([])),
      Effect.map(entries =>
        entries
          .filter(entry => entry.type === 'file' && entry.uri.toLowerCase().endsWith('.md'))
          .map(entry => entry.uri),
      ),
    ));
  const records = yield* Effect.forEach(
    selectedUris,
    uri =>
      Effect.gen(function* () {
        const content = yield* store.read(location, uri).pipe(Effect.catchTag('ResourceNotFound', () => Effect.void));
        if (content === undefined) {
          return undefined;
        }
        const record = parseMemoryDocument(uri, content);
        if (
          !record ||
          !projection.kinds.includes(record.metadata.kind) ||
          !projection.statuses.includes(record.metadata.status) ||
          (!projection.includeShared && isSharedMemoryUri(uri))
        ) {
          return undefined;
        }
        return record;
      }),
    {concurrency: MEMORY_READ_CONCURRENCY},
  );
  return records.filter((record): record is MemoryRecord => record !== undefined);
});

const desiredProjectionFiles = Effect.fn('obsidian.desiredProjectionFiles')(function* (
  projection: ObsidianProjectionConfig,
  records: readonly MemoryRecord[],
) {
  const identities = yield* Effect.forEach(
    records,
    record =>
      Effect.gen(function* () {
        const id = record.metadata.memoryId ?? `tn_${(yield* sha256Hex(record.uri)).slice(0, 20)}`;
        const relativePath = projectionMemoryPath(record, id);
        return {id, record, relativePath};
      }),
    {concurrency: MEMORY_READ_CONCURRENCY},
  );
  const projectedPathByUri = new Map(identities.map(item => [item.record.uri, item.relativePath]));
  const desired = new Map<string, DesiredProjectionFile>();
  for (const item of identities) {
    const rendered = yield* renderProjectionMemory(projection, item.record, item.id, projectedPathByUri);
    if (!rendered) {
      continue;
    }
    desired.set(item.relativePath, {
      content: rendered.content,
      contentHash: rendered.contentHash,
      relativePath: item.relativePath,
      uri: item.record.uri,
    });
  }
  for (const generated of yield* generatedProjectionFiles(projection)) {
    desired.set(generated.relativePath, generated);
  }
  return desired;
});

const renderProjectionMemory = Effect.fn('obsidian.renderProjectionMemory')(function* (
  projection: ObsidianProjectionConfig,
  record: MemoryRecord,
  memoryId: string,
  projectedPathByUri: ReadonlyMap<string, string>,
) {
  const canonical = canonicalMemoryDocumentContent(record.content);
  const sourceHash = record.metadata.sourceHash ?? `sha256:${yield* sha256Hex(canonical)}`;
  const visibility = record.metadata.visibility ?? (isSharedMemoryUri(record.uri) ? 'shared' : 'personal');
  const relations = memoryRelations(record);
  const frontmatter = {
    threadnote_schema: 1,
    threadnote_id: memoryId,
    threadnote_uri: record.uri,
    threadnote_generated: true,
    ...(record.metadata.schemaVersion !== undefined ? {threadnote_memory_schema: record.metadata.schemaVersion} : {}),
    kind: record.metadata.kind,
    status: record.metadata.status,
    ...(record.metadata.project ? {project: record.metadata.project} : {}),
    ...(record.metadata.topic ? {topic: record.metadata.topic} : {}),
    visibility,
    authority: record.metadata.authority ?? (visibility === 'shared' ? 'reviewed_shared' : 'agent_generated'),
    trust: record.metadata.trust ?? (visibility === 'shared' ? 'approved' : 'inferred'),
    created_at: record.metadata.createdAt ?? record.metadata.timestamp,
    updated_at: record.metadata.updatedAt ?? record.metadata.timestamp,
    ...(record.metadata.validFrom ? {valid_from: record.metadata.validFrom} : {}),
    ...(record.metadata.validTo ? {valid_to: record.metadata.validTo} : {}),
    ...(record.metadata.lastReviewed ? {last_reviewed: record.metadata.lastReviewed} : {}),
    source_agent_client: record.metadata.sourceAgentClient,
    source_hash: sourceHash,
    ...(record.metadata.codeCitations && record.metadata.codeCitations.length > 0
      ? {code_citations: record.metadata.codeCitations.map(formatMemoryCodeCitation)}
      : {}),
    ...(record.metadata.citationErrors && record.metadata.citationErrors.length > 0
      ? {
          code_citation_errors: record.metadata.citationErrors.map(error => ({
            ...(error.index === undefined ? {} : {index: error.index}),
            reason: error.reason,
          })),
        }
      : {}),
    relations: relations.map(relation => `${relation.type} ${relation.uri}`),
    evidence: [...(record.metadata.evidence ?? [])],
  };
  const relationLines = relations.map(relation => {
    const projected = projectedPathByUri.get(relation.uri);
    const target = projected
      ? `[[${projection.folder}/${withoutMarkdownExtension(projected)}]]`
      : `\`${relation.uri}\``;
    return `- **${relation.type.replaceAll('_', ' ')}:** ${target}  \n  \`${relation.uri}\``;
  });
  const rendered = [
    '---',
    yaml.dump(frontmatter, {lineWidth: 100, noRefs: true, sortKeys: false}).trimEnd(),
    '---',
    '',
    `<!-- ${PROJECTION_MANAGED_MARKER}:${projection.id}; do not edit -->`,
    '> [!warning] Generated view',
    '> Threadnote is authoritative. Changes to this file are not imported.',
    '',
    record.body,
    ...(relationLines.length > 0 ? ['', '## Relations', '', ...relationLines] : []),
    '',
  ].join('\n');
  const scrubbed = applyScrubber(rendered, {redact: true});
  if (scrubbed.blocker) {
    return undefined;
  }
  return {content: scrubbed.cleaned, contentHash: yield* sha256Hex(scrubbed.cleaned)};
});

const generatedProjectionFiles = Effect.fn('obsidian.generatedProjectionFiles')(function* (
  projection: ObsidianProjectionConfig,
) {
  const files = [
    {
      relativePath: 'README.md',
      content: [
        `<!-- ${PROJECTION_MANAGED_MARKER}:${projection.id}; do not edit -->`,
        '# Threadnote memory projection',
        '',
        'This folder is a generated, read-only view of authoritative Threadnote memory.',
        'Use Threadnote to create, replace, archive, or publish memories.',
        '',
      ].join('\n'),
    },
    ...projectionBaseDefinitions().map(view => ({
      relativePath: `Views/${view.filename}`,
      content: `# ${PROJECTION_MANAGED_MARKER}:${projection.id}\n${yaml.dump(view.definition, {
        lineWidth: 100,
        noRefs: true,
        sortKeys: false,
      })}`,
    })),
  ];
  return yield* Effect.forEach(files, file =>
    sha256Hex(file.content).pipe(
      Effect.map(contentHash => ({...file, contentHash, uri: undefined}) satisfies DesiredProjectionFile),
    ),
  );
});

function projectionBaseDefinitions(): ReadonlyArray<{
  readonly definition: Record<string, unknown>;
  readonly filename: string;
}> {
  const table = (filters: readonly string[]) => ({
    filters: {and: [...filters]},
    views: [
      {
        type: 'table',
        name: 'Threadnote',
        order: ['file.name', 'project', 'topic', 'status', 'updated_at'],
      },
    ],
  });
  return [
    {
      definition: table(['threadnote_generated == true', 'kind == "handoff"', 'status == "active"']),
      filename: 'Active Handoffs.base',
    },
    {
      definition: table(['threadnote_generated == true', 'kind == "durable"', 'status == "active"']),
      filename: 'Current Decisions.base',
    },
    {
      definition: table(['threadnote_generated == true', 'last_reviewed == null']),
      filename: 'Stale or Unreviewed.base',
    },
    {definition: table(['threadnote_generated == true', 'status == "superseded"']), filename: 'Contradictions.base'},
    {
      definition: table(['threadnote_generated == true', 'visibility == "shared"']),
      filename: 'Published and Shared.base',
    },
  ];
}

function projectionMemoryPath(record: MemoryRecord, memoryId: string): string {
  const project = uriSegment(record.metadata.project ?? 'unscoped');
  const topic = uriSegment(record.metadata.topic ?? uriBasename(record.uri));
  return `Memories/${project}/${record.metadata.kind}/${topic}--${memoryId.slice(-10)}.md`;
}

function memoryRelations(record: MemoryRecord): readonly MemoryRelation[] {
  const relations: MemoryRelation[] = [
    ...(record.metadata.relations ?? []),
    ...(record.metadata.references ?? []).map(uri => ({type: 'references' as const, uri})),
    ...(record.metadata.evidence ?? [])
      .filter(value => value.startsWith('threadnote://'))
      .map(uri => ({type: 'evidence_for' as const, uri})),
    ...(record.metadata.supersedes ? [{type: 'supersedes' as const, uri: record.metadata.supersedes}] : []),
  ];
  const seen = new Set<string>();
  return relations.filter(relation => {
    const key = `${relation.type}\n${relation.uri}`;
    if (seen.has(key)) {
      return false;
    }
    seen.add(key);
    return true;
  });
}

const projectionRoot = Effect.fn('obsidian.projectionRoot')(function* (projection: ObsidianProjectionConfig) {
  const pathService = yield* Path.Path;
  return pathService.join(projection.vault, ...projection.folder.split('/'));
});

const projectionStatePath = Effect.fn('obsidian.projectionStatePath')(function* (projection: ObsidianProjectionConfig) {
  const pathService = yield* Path.Path;
  return pathService.join(yield* projectionRoot(projection), PROJECTION_STATE_FILENAME);
});

export const readProjectionState = Effect.fn('obsidian.readProjectionState')(function* (
  path: string,
  projectionId: string,
) {
  const fs = yield* FileSystem.FileSystem;
  if (!(yield* fs.exists(path))) {
    return emptyProjectionState(projectionId);
  }
  const raw = yield* fs.readFileString(path);
  return yield* Effect.try({
    try: () => parseProjectionState(JSON.parse(raw), projectionId),
    catch: cause =>
      Schema.is(ObsidianProjectionError)(cause)
        ? cause
        : ObsidianProjectionError.make({cause, message: cause instanceof Error ? cause.message : String(cause)}),
  });
});

const writeProjectionState = Effect.fn('obsidian.writeProjectionState')(function* (
  path: string,
  state: ObsidianProjectionState,
) {
  const fs = yield* FileSystem.FileSystem;
  const pathService = yield* Path.Path;
  const crypto = yield* Crypto.Crypto;
  yield* fs.makeDirectory(pathService.dirname(path), {recursive: true});
  const temporaryPath = `${path}.${yield* crypto.randomUUIDv4}.tmp`;
  yield* fs.writeFileString(temporaryPath, `${JSON.stringify(state, undefined, 2)}\n`, {
    mode: PROJECTION_PRIVATE_FILE_MODE,
  });
  yield* fs
    .rename(temporaryPath, path)
    .pipe(Effect.ensuring(fs.remove(temporaryPath, {force: true}).pipe(Effect.ignore)));
  yield* fs.chmod(path, PROJECTION_PRIVATE_FILE_MODE);
});

function parseProjectionState(value: unknown, projectionId: string): ObsidianProjectionState {
  if (
    typeof value !== 'object' ||
    value === null ||
    !('version' in value) ||
    value.version !== PROJECTION_STATE_VERSION ||
    !('projectionId' in value) ||
    value.projectionId !== projectionId ||
    !('files' in value) ||
    typeof value.files !== 'object' ||
    value.files === null
  ) {
    throw ObsidianProjectionError.make({message: `Invalid Obsidian projection state for "${projectionId}".`});
  }
  const files: Record<string, ObsidianProjectionFileState> = {};
  for (const [relativePath, entry] of Object.entries(value.files)) {
    assertSafeProjectionRelativePath(relativePath);
    if (
      typeof entry !== 'object' ||
      entry === null ||
      !('contentHash' in entry) ||
      typeof entry.contentHash !== 'string'
    ) {
      throw ObsidianProjectionError.make({message: `Invalid Obsidian projection state entry "${relativePath}".`});
    }
    files[relativePath] = {
      contentHash: entry.contentHash,
      uri: 'uri' in entry && typeof entry.uri === 'string' ? entry.uri : undefined,
    };
  }
  return {
    files,
    projectionId,
    syncedAt: 'syncedAt' in value && typeof value.syncedAt === 'string' ? value.syncedAt : undefined,
    version: PROJECTION_STATE_VERSION,
  };
}

function emptyProjectionState(projectionId: string): ObsidianProjectionState {
  return {files: {}, projectionId, version: PROJECTION_STATE_VERSION};
}

const writeProjectionFile = Effect.fn('obsidian.writeProjectionFile')(function* (
  root: string,
  file: DesiredProjectionFile,
) {
  const fs = yield* FileSystem.FileSystem;
  const pathService = yield* Path.Path;
  const crypto = yield* Crypto.Crypto;
  const target = yield* safeProjectionTarget(root, file.relativePath);
  yield* fs.makeDirectory(pathService.dirname(target), {recursive: true});
  const temporaryPath = `${target}.${yield* crypto.randomUUIDv4}.tmp`;
  yield* fs.writeFileString(temporaryPath, file.content, {mode: PROJECTION_NOTE_FILE_MODE});
  yield* fs
    .rename(temporaryPath, target)
    .pipe(Effect.ensuring(fs.remove(temporaryPath, {force: true}).pipe(Effect.ignore)));
  yield* fs.chmod(target, PROJECTION_NOTE_FILE_MODE);
});

const safeProjectionTarget = Effect.fn('obsidian.safeProjectionTarget')(function* (root: string, relativePath: string) {
  assertSafeProjectionRelativePath(relativePath);
  const pathService = yield* Path.Path;
  const target = pathService.resolve(root, ...relativePath.split('/'));
  const relative = pathService.relative(pathService.resolve(root), target);
  if (relative === '..' || relative.startsWith(`..${pathService.sep}`) || pathService.isAbsolute(relative)) {
    return yield* ObsidianProjectionError.make({
      message: `Projection path escapes its managed folder: ${relativePath}`,
    });
  }
  return target;
});

function assertSafeProjectionRelativePath(relativePath: string): void {
  const normalized = toPosixPath(relativePath);
  if (
    normalized.length === 0 ||
    normalized.startsWith('/') ||
    normalized.split('/').some(segment => segment === '' || segment === '.' || segment === '..')
  ) {
    throw ObsidianProjectionError.make({message: `Unsafe projection state path: ${relativePath}`});
  }
}

function fileContentHash(
  fs: FileSystem.FileSystem,
  path: string,
): Effect.Effect<string | undefined, never, Crypto.Crypto> {
  return fs.readFile(path).pipe(Effect.flatMap(sha256Hex), Effect.option, Effect.map(Option.getOrUndefined));
}

const removeEmptyProjectionDirectories = Effect.fn('obsidian.removeEmptyProjectionDirectories')(function* (
  root: string,
) {
  const fs = yield* FileSystem.FileSystem;
  const removeIfEmpty = (path: string): Effect.Effect<void, never> =>
    Effect.gen(function* () {
      const names = yield* fs.readDirectory(path).pipe(Effect.orElseSucceed(() => []));
      if (names.length === 0) {
        yield* fs.remove(path, {force: true}).pipe(Effect.ignore);
      }
    });
  yield* removeIfEmpty(root);
});

const canonicalDirectory = Effect.fn('obsidian.projectionCanonicalDirectory')(function* (value: string, label: string) {
  const fs = yield* FileSystem.FileSystem;
  const expanded = yield* expandPath(value);
  if (!(yield* isDirectory(expanded))) {
    return yield* ObsidianProjectionError.make({message: `${label} is not a directory: ${expanded}`});
  }
  return yield* fs.realPath(expanded);
});

function normalizeProjectionFolder(value: string): string {
  const normalized = toPosixPath(value).replace(/^\/+|\/+$/g, '');
  if (
    normalized.length === 0 ||
    normalized.split('/').some(segment => segment === '' || segment === '.' || segment === '..')
  ) {
    throw ObsidianProjectionError.make({message: 'Projection folder must be a safe vault-relative path.'});
  }
  return normalized;
}

function normalizeIdentifier(value: string, label: string): string {
  const normalized = value.trim().toLowerCase();
  if (!/^[a-z0-9][a-z0-9._-]*$/.test(normalized)) {
    throw ObsidianProjectionError.make({
      message: `${label} must contain only lowercase letters, digits, dots, underscores, and hyphens.`,
    });
  }
  return normalized;
}

function projectionSummary(projection: ObsidianProjectionConfig): string {
  return [
    `${projection.id} · ${projection.enabled ? 'enabled' : 'disabled'} · ${projection.vault}/${projection.folder}`,
    `  selected memories: ${projection.selectedUris?.length ?? 'all matching (legacy)'}`,
    `  kinds: ${projection.kinds.join(', ')}`,
    `  statuses: ${projection.statuses.join(', ')}`,
    `  shared: ${projection.includeShared ? 'included' : 'excluded'}`,
  ].join('\n');
}

const printProjectionPlan = Effect.fn('obsidian.printProjectionPlan')(function* (plan: ProjectionPlan) {
  if (plan.entries.length === 0) {
    yield* Console.log(`Obsidian projection "${plan.projection.id}" has no files to change.`);
    return;
  }
  for (const entry of plan.entries) {
    yield* Console.log(
      `${entry.action.toUpperCase().padEnd(9)} ${entry.relativePath}${entry.detail ? ` (${entry.detail})` : ''}`,
    );
  }
  const counts = projectionCounts(plan.entries);
  yield* Console.log(
    `Projection: ${counts.add} add, ${counts.update} update, ${counts.remove} remove, ` +
      `${counts.unchanged} unchanged, ${counts.drift} drift, ${counts.skip} skipped.`,
  );
});

function projectionCounts(entries: readonly ObsidianProjectionEntry[]): Record<ObsidianProjectionAction, number> {
  const counts: Record<ObsidianProjectionAction, number> = {
    add: 0,
    drift: 0,
    remove: 0,
    skip: 0,
    unchanged: 0,
    update: 0,
  };
  for (const entry of entries) {
    counts[entry.action] += 1;
  }
  return counts;
}

function projectionActionRank(action: ObsidianProjectionAction): number {
  return {add: 0, update: 1, remove: 2, drift: 3, skip: 4, unchanged: 5}[action];
}

function uriBasename(uri: string): string {
  const withoutAnchor = uri.replace(/#.*$/, '').replace(/\/+$/, '');
  return withoutAnchor.slice(withoutAnchor.lastIndexOf('/') + 1).replace(/\.md$/i, '');
}

function normalizeProjectionMemoryUris(
  config: Pick<RuntimeConfig, 'user'>,
  values: readonly string[],
): readonly string[] {
  if (values.length === 0) {
    throw ObsidianProjectionError.make({message: 'Provide at least one Threadnote memory URI with --uri.'});
  }
  const expectedUser = uriSegment(config.user);
  return [...new Set(values.map(value => canonicalProjectionMemoryUri(value, expectedUser)))].sort((left, right) =>
    left.localeCompare(right),
  );
}

function canonicalProjectionMemoryUri(value: string, expectedUser: string): string {
  const parsed = parseResourceId(value);
  if (parsed.anchor) {
    throw ObsidianProjectionError.make({
      message: `Obsidian projections require whole-memory URIs without anchors: ${value}`,
    });
  }
  const canonical = resourceIdWithoutAnchor(parsed);
  if (
    canonical.namespace !== 'user' ||
    canonical.segments[0] !== expectedUser ||
    canonical.segments[1] !== 'memories' ||
    canonical.segments.length < 3 ||
    !canonical.segments.at(-1)?.toLowerCase().endsWith('.md')
  ) {
    throw ObsidianProjectionError.make({
      message: `Obsidian projections accept only current-user Threadnote memory URIs: ${value}`,
    });
  }
  return canonical.canonicalUri;
}

function withoutMarkdownExtension(path: string): string {
  return path.replace(/\.md$/i, '');
}

function resourceStoreLocation(config: Pick<RuntimeConfig, 'account' | 'agentContextHome' | 'user'>) {
  return {
    account: config.account,
    home: config.agentContextHome,
    user: config.user,
  } as const;
}
