export type {
  AutoShareSyncResult,
  ChangedFile,
  ResolvedTeam,
  ShareArtifactMetadata,
  ShareArtifactResult,
  ShareConflictDetail,
  ShareConflictResolveResult,
  ShareConflictSummary,
  SharedArtifactFile,
  SharedArtifactInstallResult,
  SharedArtifactInstallStatus,
  SharedArtifactListResult,
  SharedArtifactSummary,
  SharedMemoryUriParts,
} from './core.js';
export {
  clearAutoShareStateForTest,
  assertShareTeamWritable,
  DEFAULT_GIT_REMOTE_NAME,
  ensureSharedDirectoryChain,
  isInSharedNamespace,
  markSharedAutoSyncDeferred,
  normalizeTeamName,
  parentUri,
  personalUriFor,
  establishedSharedMemoryIdentity,
  reconcileMissingSharedMemoryIdentity,
  sharedMemoryIdentityConflict,
  readTeamsFile,
  removeMemoryUri,
  resolveTeam,
  resourceExists,
  resourceUriToWorktreeRelative,
  setMemoryVisibility,
  SHARED_BACKGROUND_FETCH_INTERVAL_MILLISECONDS,
  sharedDirectoryChain,
  sharedMemoryUriParts,
  sharedTeamNameForUri,
  sharedUriFor,
  shareTeamAccess,
  stripPersonalProvenance,
  stripPersonalProvenanceForSharedPublication,
  writeMemoryFile,
  writeMemoryFileChecked,
} from './core.js';
export {
  runShareInit,
  runShareList,
  runShareRemove,
  runShareRename,
  runShareSetAccess,
  runShareSetUrl,
  runShareStatus,
  runShareUnpublish,
  shareUnpublishTargetDisposition,
} from './admin.js';
export {refreshSharedReposInBackground, runShareSync, syncSharedReposBeforeAgentRead} from './sync.js';
export {
  listShareConflicts,
  resolveShareConflict,
  runShareConflictResolve,
  runShareConflicts,
  runShareConflictShow,
  shareConflictCanTakeShared,
  showShareConflict,
} from './conflicts.js';
export {
  assertSharedWorktreeFileReady,
  listChangedFiles,
  mergeChanges,
  publishShareGitChange,
  writeSharedWorktreeFile,
} from './git.js';
export {
  runSharePublish,
  runSharePublishArtifact,
  runSharePublishBundle,
  shareAgentArtifact,
  shareBundlePack,
} from './artifact/publish.js';
export {installSharedAgentArtifacts, listSharedAgentArtifacts, runShareInstallArtifacts} from './artifact/install.js';
export {applyScrubber, scrubberBlocker} from '@threadnote/platform/scrubber';
