export const DEFAULT_ACCOUNT = 'local';
export const DEFAULT_AGENT_ID = 'threadnote';
export const THREADNOTE_MCP_NAME = 'threadnote';
export const THREADNOTE_MCP_CLIENT_ENV = 'THREADNOTE_MCP_CLIENT';
export const THREADNOTE_MCP_SURFACE_ENV = 'THREADNOTE_MCP_SURFACE';
export const MCP_PROCESS_LIFECYCLE_PROBE_ENV = 'THREADNOTE_MCP_PROCESS_LIFECYCLE_PROBE';
export const MAX_SECRET_MATCHES_TO_PRINT = 5;
export const SHIM_MARKER = 'Generated by threadnote';
export const USER_INSTRUCTIONS_START_MARKER = '<!-- BEGIN THREADNOTE USER INSTRUCTIONS -->';
export const USER_INSTRUCTIONS_END_MARKER = '<!-- END THREADNOTE USER INSTRUCTIONS -->';
export {USER_MANIFEST_NAME, SEED_STATE_FILE} from '@threadnote/workspace/constants';
export const LEGACY_CURSOR_INSTRUCTION_PATHS = [
  '~/.cursor/rules/threadnote.md',
  '~/.cursor/rules/threadnote.mdc',
] as const;

export const CLAUDE_SETTINGS_PATH = '~/.claude/settings.json';
export const CODEX_HOOKS_PATH = '~/.codex/hooks.json';
export const THREADNOTE_HOOK_MARKER = '_threadnote';
export const THREADNOTE_HOOK_MARKER_VALUE = 'managed';
export const HOOK_PRE_COMPACT_COMMAND = 'threadnote pre-compact-hook';
export const HOOK_SESSION_START_COMMAND = 'threadnote session-start-hook';
export const HOOK_CODE_BRIEF_COMMAND = 'threadnote code-brief-hook';
export const HOOK_CODEX_RESUME_COMMAND = 'threadnote codex-resume-hook';
export const THREADNOTE_CODEX_RESUME_PRELOAD_ENV = 'THREADNOTE_CODEX_RESUME_PRELOAD';
export const HOOK_AUTO_PRECOMPACT_TOPIC = 'auto-precompact';
export const DEFAULT_SEED_PATTERNS = [
  'AGENTS.md',
  'CLAUDE.md',
  'README.md',
  'CONTRIBUTING.md',
  '.github/AGENTS.md',
  '.github/CLAUDE.md',
  '.github/pull_request_template.md',
  '.github/PULL_REQUEST_TEMPLATE.md',
  '.github/PULL_REQUEST_TEMPLATE/*.md',
  '.claude/commands/*.md',
  '.claude/skills/**/SKILL.md',
  '.claude/**/*.md',
  '.agents/**/*.md',
  'docs/**/*.md',
] as const;
