export {
  CODE_GRAPH_ANALYSIS_WORKER_ARGUMENT,
  CODE_GRAPH_PARSER_WORKER_ARGUMENT,
  CODE_GRAPH_DEEP_DIAGNOSTICS_WORKER_ARGUMENT,
  CODE_GRAPH_IMPACT_QUERY_WORKER_ARGUMENT,
  CODE_GRAPH_COMPACTION_WORKER_ARGUMENT,
  CODE_GRAPH_GIT_WORKTREE_REGISTRATION_WORKER_ARGUMENT,
} from '@threadnote/graph/worker_protocol';
export {
  WINDOWS_DISK_CAPACITY_WORKER_ARGUMENT,
  WINDOWS_DISK_CAPACITY_WORKER_PROTOCOL_VERSION,
} from '@threadnote/platform/windows-disk-worker-contract';
export const LOCAL_MODEL_WORKER_ARGUMENT = '--threadnote-local-model-worker';
export const INTEGRATION_SYNC_WORKER_ARGUMENT = '--threadnote-integration-sync-worker';
