#!/usr/bin/env sh
set -eu

REPOSITORY="${THREADNOTE_REPOSITORY:-threadnote/threadnote}"
CHANNEL="${THREADNOTE_CHANNEL:-latest}"
RELEASES_API="${THREADNOTE_RELEASE_SOURCE:-https://api.github.com/repos/$REPOSITORY/releases?per_page=100}"
INSTALL_LOCK_WAIT_SECONDS=600
INSTALL_LOCK_STALE_SECONDS=60
installation_lock_path=""
installation_lock_token=""

argument_count=$#
while [ "$argument_count" -gt 0 ]; do
  argument="$1"
  shift
  case "$argument" in
    --beta) CHANNEL=beta ;;
    *) set -- "$@" "$argument" ;;
  esac
  argument_count=$((argument_count - 1))
done

say() {
  printf '%s\n' "$*"
}

die() {
  say "ERROR: $*" >&2
  exit 1
}

have() {
  command -v "$1" >/dev/null 2>&1
}

is_official_repository() {
  case "$1" in
    Kashkovsky/threadnote | threadnote/threadnote) return 0 ;;
    *) return 1 ;;
  esac
}

require_command() {
  have "$1" || die "$1 is required to install Threadnote."
}

path_contains_directory() (
  path_candidate="$1"
  path_remainder="${PATH:-}:"
  while [ -n "$path_remainder" ]; do
    path_entry="${path_remainder%%:*}"
    path_remainder="${path_remainder#*:}"
    [ "$path_entry" != "$path_candidate" ] || return 0
  done
  return 1
)

shell_quote() {
  printf "'"
  printf '%s' "$1" | sed "s/'/'\\\\''/g"
  printf "'"
}

canonical_launcher_quote() {
  launcher_quote_value="$1"
  if printf '%s' "$launcher_quote_value" | grep -Eq '^[A-Za-z0-9_./:@=-]+$'; then
    printf '%s' "$launcher_quote_value"
    return
  fi
  printf "'"
  printf '%s' "$launcher_quote_value" | sed "s/'/'\"'\"'/g"
  printf "'"
}

normalize_relative_path() {
  awk -F / '
    {
      depth = 0
      for (index_ = 1; index_ <= NF; index_++) {
        component = $index_
        if (component == "" || component == ".") continue
        if (component == "..") {
          if (depth > 0) depth--
        } else {
          components[++depth] = component
        }
      }
      result = "/"
      for (index_ = 1; index_ <= depth; index_++)
        result = result (index_ == 1 ? "" : "/") components[index_]
      print result
    }
  '
}

render_expected_launcher() {
  launcher_mode="$1"
  launcher_executable="$2"
  launcher_entry="$(canonical_launcher_quote "$launcher_executable")"
  case "$launcher_mode" in
    cli) launcher_mode_argument="" ;;
    mcp) launcher_mode_argument=" mcp-broker" ;;
    credential-oauth-m2m) launcher_mode_argument=" __credential-oauth-m2m" ;;
    credential-registry-oauth-m2m) launcher_mode_argument=" __credential-registry-oauth-m2m" ;;
    credential-registry-oauth-publisher-m2m) launcher_mode_argument=" __credential-registry-oauth-publisher-m2m" ;;
    credential-auth0-m2m) launcher_mode_argument=" __credential-auth0-m2m" ;;
    credential-registry-auth0-m2m) launcher_mode_argument=" __credential-registry-auth0-m2m" ;;
    credential-registry-auth0-publisher-m2m) launcher_mode_argument=" __credential-registry-auth0-publisher-m2m" ;;
    credential-registry-oauth-user) launcher_mode_argument=" __credential-registry-oauth-user" ;;
    credential-registry-auth0-user) launcher_mode_argument=" __credential-registry-auth0-user" ;;
    *) die "Unknown launcher mode: $launcher_mode" ;;
  esac
  printf '%s\n' \
    '#!/usr/bin/env sh' \
    '# Generated by threadnote' \
    'set -eu' \
    "THREADNOTE_ENTRY=$launcher_entry" \
    'if [ ! -x "$THREADNOTE_ENTRY" ]; then' \
    '  echo "Threadnote standalone executable is missing: $THREADNOTE_ENTRY" >&2' \
    '  echo "Reinstall Threadnote from a stable or beta GitHub release." >&2' \
    '  exit 127' \
    'fi' \
    'THREADNOTE_CALLER_CWD="$PWD"' \
    'export THREADNOTE_CALLER_CWD' \
    "exec \"\$THREADNOTE_ENTRY\"$launcher_mode_argument \"\$@\""
}

verify_managed_launcher() {
  verified_launcher_path="$1"
  verified_launcher_mode="$2"
  verified_launcher_expected="$3"
  verified_launcher_rendered="$4"
  [ -x "$verified_launcher_path" ] || die "Threadnote did not install its $verified_launcher_mode launcher at $verified_launcher_path."
  render_expected_launcher "$verified_launcher_mode" "$verified_launcher_expected" >"$verified_launcher_rendered"
  if ! cmp -s "$verified_launcher_rendered" "$verified_launcher_path"; then
    die "The $verified_launcher_mode launcher at $verified_launcher_path is not managed by this Threadnote release and was not replaced."
  fi
}

configure_default_command_path() {
  launcher_directory="$HOME/.local/bin"
  path_contains_directory "$launcher_directory" && return 0

  configured_shell="${SHELL:-}"
  shell_name="${configured_shell##*/}"
  current_shell_path_command='export PATH="$HOME/.local/bin:$PATH"'
  path_profile_block='case ":$PATH:" in
  *:"$HOME/.local/bin":*) ;;
  *) export PATH="$HOME/.local/bin:$PATH" ;;
esac'
  case "$shell_name" in
    zsh) path_profile="$HOME/.zshrc" ;;
    bash)
      if [ "$(uname -s 2>/dev/null || true)" = Darwin ]; then
        path_profile="$HOME/.bash_profile"
      else
        path_profile="$HOME/.bashrc"
      fi
      ;;
    fish)
      path_profile="$HOME/.config/fish/config.fish"
      path_profile_block='fish_add_path "$HOME/.local/bin"'
      current_shell_path_command='set -gx PATH "$HOME/.local/bin" $PATH'
      ;;
    *) path_profile="$HOME/.profile" ;;
  esac

  path_profile_parent="${path_profile%/*}"
  [ "$path_profile_parent" = "$path_profile" ] || mkdir -p "$path_profile_parent"
  if [ -f "$path_profile" ] && grep -F '# >>> threadnote command path >>>' "$path_profile" >/dev/null 2>&1; then
    say "Command directory is already referenced by $path_profile"
  else
    {
      [ ! -s "$path_profile" ] || printf '\n'
      printf '%s\n' '# >>> threadnote command path >>>'
      printf '%s\n' "$path_profile_block"
      printf '%s\n' '# <<< threadnote command path <<<'
    } >>"$path_profile"
    say "Added ~/.local/bin to PATH in $path_profile"
  fi

  say "The installer cannot change the current parent shell."
  say "Open a new terminal, or run this now:"
  say "  $current_shell_path_command"
}

verify_code_signature() {
  signature_target="$1"
  if ! signature_output="$(codesign --verify --strict --verbose=2 "$signature_target" 2>&1)"; then
    [ -z "$signature_output" ] || printf '%s\n' "$signature_output" >&2
    die "Release signature validation failed for $signature_target."
  fi
}

process_start_identity() {
  process_id="$1"
  case "$(uname -s 2>/dev/null || true)" in
    Linux)
      [ -r "/proc/$process_id/stat" ] || return 0
      identity="$(
        sed 's/^.*) //' "/proc/$process_id/stat" 2>/dev/null |
          awk 'NF >= 20 { print "linux:" $20; exit }'
      )"
      ;;
    Darwin)
      identity="$(ps -o lstart= -p "$process_id" 2>/dev/null | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' || true)"
      [ -z "$identity" ] || identity="darwin:$identity"
      ;;
    *) identity="" ;;
  esac
  printf '%s' "$identity"
}

lock_owner_pid() {
  token="$1"
  case "$token" in
    \{*)
      printf '%s' "$token" |
        sed -n 's/.*"processId"[[:space:]]*:[[:space:]]*\([0-9][0-9]*\).*/\1/p'
      ;;
    *) printf '%s' "${token%%:*}" ;;
  esac
}

lock_owner_start_identity() {
  token="$1"
  case "$token" in
    \{*)
      printf '%s' "$token" |
        sed -n 's/.*"processStartIdentity"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p'
      ;;
  esac
}

lock_modified_epoch() {
  lock_path="$1"
  case "$(uname -s 2>/dev/null || true)" in
    Darwin) stat -f '%m' "$lock_path" 2>/dev/null || true ;;
    *) stat -c '%Y' "$lock_path" 2>/dev/null || true ;;
  esac
}

lock_file_signature() {
  lock_path="$1"
  case "$(uname -s 2>/dev/null || true)" in
    Darwin) stat -f '%i:%m:%z' "$lock_path" 2>/dev/null || true ;;
    *) stat -c '%i:%Y:%s' "$lock_path" 2>/dev/null || true ;;
  esac
}

release_installation_lock() {
  [ -n "$installation_lock_path" ] || return 0
  observed="$(sed -n '1p' "$installation_lock_path" 2>/dev/null || true)"
  if [ "$observed" = "$installation_lock_token" ]; then
    rm -f -- "$installation_lock_path"
  fi
  installation_lock_path=""
  installation_lock_token=""
}

acquire_installation_lock() {
  installation_lock_path="$1"
  owner_start_identity="$(process_start_identity "$$")"
  if [ -n "$owner_start_identity" ]; then
    installation_lock_token="{\"processId\":$$,\"processStartIdentity\":\"$owner_start_identity\",\"token\":\"bootstrap-installer\",\"version\":1}"
  else
    installation_lock_token="{\"processId\":$$,\"token\":\"bootstrap-installer\",\"version\":1}"
  fi
  started_at="$(date +%s)"
  while ! (
    umask 077
    set -C
    printf '%s\n' "$installation_lock_token" >"$installation_lock_path"
  ) 2>/dev/null; do
    observed="$(sed -n '1p' "$installation_lock_path" 2>/dev/null || true)"
    owner_pid="$(lock_owner_pid "$observed")"
    now="$(date +%s)"
    case "$owner_pid" in
      '' | *[!0-9]*)
        modified_at="$(lock_modified_epoch "$installation_lock_path")"
        observed_signature="$(lock_file_signature "$installation_lock_path")"
        case "$modified_at" in
          '' | *[!0-9]*) ;;
          *)
            if [ $((now - modified_at)) -ge "$INSTALL_LOCK_STALE_SECONDS" ]; then
              current="$(sed -n '1p' "$installation_lock_path" 2>/dev/null || true)"
              current_signature="$(lock_file_signature "$installation_lock_path")"
              if [ -n "$observed_signature" ] &&
                [ "$current" = "$observed" ] &&
                [ "$current_signature" = "$observed_signature" ]; then
                rm -f -- "$installation_lock_path"
                continue
              fi
            fi
            ;;
        esac
        ;;
      *)
        owner_is_stale=false
        if ! kill -0 "$owner_pid" 2>/dev/null; then
          owner_is_stale=true
        else
          recorded_start_identity="$(lock_owner_start_identity "$observed")"
          if [ -n "$recorded_start_identity" ]; then
            current_start_identity="$(process_start_identity "$owner_pid")"
            if [ -n "$current_start_identity" ] && [ "$current_start_identity" != "$recorded_start_identity" ]; then
              owner_is_stale=true
            fi
          fi
        fi
        if [ "$owner_is_stale" = true ]; then
          current="$(sed -n '1p' "$installation_lock_path" 2>/dev/null || true)"
          if [ "$current" = "$observed" ]; then
            rm -f -- "$installation_lock_path"
            continue
          fi
        fi
        ;;
    esac
    [ $((now - started_at)) -lt "$INSTALL_LOCK_WAIT_SECONDS" ] ||
      die "Timed out waiting for Threadnote installation lock: $installation_lock_path"
    sleep 1
  done
}

cleanup() {
  rm -rf -- "$temporary_root"
  [ -z "$staged_root" ] || rm -rf -- "$staged_root"
  release_installation_lock
}

release_objects() {
  awk '
    BEGIN { depth = 0; in_string = 0; escaped = 0; object = "" }
    {
      for (position = 1; position <= length($0); position++) {
        character = substr($0, position, 1)
        if (depth > 0) object = object character
        if (in_string) {
          if (escaped) escaped = 0
          else if (character == "\\") escaped = 1
          else if (character == "\"") in_string = 0
          continue
        }
        if (character == "\"") {
          in_string = 1
          continue
        }
        if (character == "{") {
          if (depth == 0) object = "{"
          depth++
        } else if (character == "}") {
          depth--
          if (depth == 0) {
            print object
            object = ""
          }
        }
      }
    }
  '
}

resolve_version() {
  requested_version="${THREADNOTE_VERSION:-}"
  requested_version="${requested_version#v}"
  if [ -z "$requested_version" ]; then
    case "$CHANNEL" in
      latest | stable) prerelease=false ;;
      beta) prerelease=any ;;
      *) die "THREADNOTE_CHANNEL must be latest, stable, or beta." ;;
    esac
  else
    prerelease=any
  fi
  releases="$(fetch_release_json "$RELEASES_API")"
  version=$(
    printf '%s' "$releases" |
      release_objects |
      awk -v desired="$prerelease" -v requested="$requested_version" '
        function greater(candidate, current, candidate_core, current_core, candidate_dash, current_dash,
          candidate_parts, current_parts, candidate_pre, current_pre, candidate_ids, current_ids,
          candidate_count, current_count, count, index_, candidate_id, current_id, candidate_numeric, current_numeric) {
          if (current == "") return 1
          candidate_dash = index(candidate, "-")
          current_dash = index(current, "-")
          candidate_core = candidate_dash ? substr(candidate, 1, candidate_dash - 1) : candidate
          current_core = current_dash ? substr(current, 1, current_dash - 1) : current
          split(candidate_core, candidate_parts, ".")
          split(current_core, current_parts, ".")
          for (index_ = 1; index_ <= 3; index_++) {
            if ((candidate_parts[index_] + 0) != (current_parts[index_] + 0))
              return (candidate_parts[index_] + 0) > (current_parts[index_] + 0)
          }
          if (!candidate_dash && current_dash) return 1
          if (candidate_dash && !current_dash) return 0
          if (!candidate_dash) return 0
          candidate_pre = substr(candidate, candidate_dash + 1)
          current_pre = substr(current, current_dash + 1)
          candidate_count = split(candidate_pre, candidate_ids, ".")
          current_count = split(current_pre, current_ids, ".")
          count = candidate_count < current_count ? candidate_count : current_count
          for (index_ = 1; index_ <= count; index_++) {
            candidate_id = candidate_ids[index_]
            current_id = current_ids[index_]
            if (candidate_id == current_id) continue
            candidate_numeric = candidate_id ~ /^[0-9]+$/
            current_numeric = current_id ~ /^[0-9]+$/
            if (candidate_numeric && current_numeric) return (candidate_id + 0) > (current_id + 0)
            if (candidate_numeric != current_numeric) return !candidate_numeric
            return candidate_id > current_id
          }
          return candidate_count > current_count
        }
        {
          compact = $0
          gsub(/[[:space:]]/, "", compact)
        }
        index(compact, "\"draft\":false") && index(compact, "\"immutable\":true") {
          candidate_prerelease = index(compact, "\"prerelease\":true") ? "true" : "false"
          count = split(compact, fields, "\"")
          for (field = 1; field < count; field++) {
            if (fields[field] == "tag_name") {
              tag = fields[field + 2]
              sub(/^v/, "", tag)
              if (tag !~ /^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$/) continue
              if (requested != "") {
                if (tag == requested) best = tag
              } else if ((desired == "any" || candidate_prerelease == desired) && greater(tag, best)) {
                best = tag
              }
            }
          }
        }
        END { if (best != "") print best }
      '
  )
  if [ -z "$version" ] && [ -n "$requested_version" ]; then
    die "Threadnote $requested_version is not a published immutable release."
  fi
  [ -n "$version" ] || die "No immutable $CHANNEL Threadnote release is currently published."
  printf '%s' "$version"
}

platform_name() {
  case "$(uname -s)" in
    Darwin) printf '%s' darwin ;;
    Linux) printf '%s' linux ;;
    *) die "Threadnote standalone releases support macOS, Linux, and Windows." ;;
  esac
}

architecture_name() {
  case "$(uname -m)" in
    arm64 | aarch64) printf '%s' arm64 ;;
    x86_64 | amd64) printf '%s' x64 ;;
    *) die "Threadnote standalone releases support arm64 and x64." ;;
  esac
}

sha256_file() {
  if have sha256sum; then
    sha256sum "$1" | awk '{print $1}'
  elif have shasum; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    die "sha256sum or shasum is required to verify Threadnote."
  fi
}

fetch_release_json() {
  curl -fsSL \
    --retry 3 \
    --retry-delay 1 \
    --retry-max-time 90 \
    --connect-timeout 15 \
    --max-time 60 \
    -H 'Accept: application/vnd.github+json' \
    -H 'User-Agent: threadnote-installer' \
    "$1"
}

download_release_file() {
  curl -fsSL \
    --retry 3 \
    --retry-delay 1 \
    --retry-max-time 180 \
    --connect-timeout 15 \
    --max-time 900 \
    "$1" \
    -o "$2"
}

validate_release_archive() {
  archive_path="$1"
  entry_list="$temporary_root/archive-entries.txt"
  verbose_list="$temporary_root/archive-entries-verbose.txt"
  LC_ALL=C tar -tzf "$archive_path" >"$entry_list" || die "Could not inspect the release archive."
  LC_ALL=C tar -tvzf "$archive_path" >"$verbose_list" || die "Could not inspect release archive entry types."
  awk '
    function reject(message) {
      print "Unsafe release archive: " message > "/dev/stderr"
      exit 1
    }
    function validate_path(value, label, count, index_, component, depth, components) {
      if (value == "") reject(label " is empty")
      if (substr(value, 1, 1) == "/" || substr(value, 1, 1) == "\\" || value ~ /^[A-Za-z]:/ || index(value, "\\") > 0)
        reject(label " is absolute or uses a platform-specific separator: " value)
      count = split(value, components, "/")
      depth = 0
      for (index_ = 1; index_ <= count; index_++) {
        component = components[index_]
        if (component == "" || component == ".") continue
        if (component == "..") {
          if (depth == 0) reject(label " escapes the extraction root: " value)
          depth--
        } else {
          depth++
        }
      }
    }
    FILENAME == ARGV[1] {
      names[++name_count] = $0
      validate_path($0, "entry path")
      next
    }
    {
      verbose_count++
      name = names[verbose_count]
      if (name == "") reject("verbose listing does not match the entry listing")
      type = substr($0, 1, 1)
      if (type != "-" && type != "d")
        reject("unsupported entry type " type " for " name)
    }
    END {
      if (name_count == 0) reject("archive is empty")
      if (name_count != verbose_count) reject("archive listings have different entry counts")
    }
  ' "$entry_list" "$verbose_list" || die "Release archive validation failed."
}

json_escape() {
  awk '
    BEGIN { ORS = ""; first = 1 }
    {
      gsub(/\\/, "\\\\")
      gsub(/"/, "\\\"")
      gsub(/\r/, "\\r")
      gsub(/\t/, "\\t")
      if (!first) printf "\\n"
      printf "%s", $0
      first = 0
    }
  '
}

write_promotion_journal() {
  journal_temporary="$promotion_journal.$$"
  escaped_release_root="$(printf '%s' "$release_root" | json_escape)"
  escaped_backup_root="$(printf '%s' "$backup_root" | json_escape)"
  escaped_staged_root="$(printf '%s' "$staged_root" | json_escape)"
  (
    umask 077
    printf '{"backupRoot":"%s","releaseRoot":"%s","stagedRoot":"%s","version":1}\n' \
      "$escaped_backup_root" \
      "$escaped_release_root" \
      "$escaped_staged_root" >"$journal_temporary"
  )
  mv "$journal_temporary" "$promotion_journal"
}

recover_release_promotion() {
  if [ -e "$backup_root" ]; then
    if [ -e "$release_root" ]; then
      rm -rf -- "$backup_root"
    else
      mv "$backup_root" "$release_root"
    fi
  fi
  rm -rf -- "$staged_root"
  rm -f -- "$promotion_journal"
}

fail_after_promotion_step_if_requested() {
  requested_step="${THREADNOTE_INSTALLER_FAIL_AFTER_PROMOTION_STEP:-}"
  [ "$requested_step" != "$1" ] || die "Injected installer interruption after promotion step: $1"
}

require_command curl
require_command cmp
require_command tar
version="$(resolve_version)"
printf '%s\n' "$version" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$' ||
  die "Resolved release version is invalid."
platform="$(platform_name)"
architecture="$(architecture_name)"
artifact="threadnote-$platform-$architecture.tar.gz"
tag="v$version"
download_root="${THREADNOTE_RELEASE_DOWNLOAD_ROOT:-https://github.com/$REPOSITORY/releases/download/$tag}"
temporary_root="$(mktemp -d "${TMPDIR:-/tmp}/threadnote-install.XXXXXX")"
staged_root=""
trap cleanup EXIT HUP INT TERM
archive="$temporary_root/$artifact"
checksum_file="$archive.sha256"

say "Downloading Threadnote $version for $platform-$architecture"
download_release_file "$download_root/$artifact" "$archive"
download_release_file "$download_root/$artifact.sha256" "$checksum_file"
expected="$(awk 'NF {print tolower($1); exit}' "$checksum_file")"
checksum_name="$(awk 'NF {name=$2; sub(/^\\*/, "", name); print name; exit}' "$checksum_file")"
actual="$(sha256_file "$archive" | tr '[:upper:]' '[:lower:]')"
[ "${#expected}" -eq 64 ] || die "Release checksum document is invalid."
[ -z "$checksum_name" ] || [ "$checksum_name" = "$artifact" ] ||
  die "Release checksum document names $checksum_name instead of $artifact."
[ "$expected" = "$actual" ] || die "Checksum verification failed for $artifact."
validate_release_archive "$archive"

install_root="${THREADNOTE_INSTALL_ROOT:-$HOME/.local/share/threadnote}"
versions_root="$install_root/versions"
release_root="$versions_root/$version"
staged_root="$versions_root/.$version.bootstrap.staging"
backup_root="$versions_root/.$version.promotion-backup"
promotion_journal="$versions_root/.$version.promotion.json"
mkdir -p "$versions_root"
acquire_installation_lock "$install_root/.installation.lock"
recover_release_promotion
mkdir -p "$staged_root"
tar -xzf "$archive" -C "$staged_root"
[ -x "$staged_root/threadnote" ] || chmod 755 "$staged_root/threadnote"
[ -f "$staged_root/release.json" ] || die "Release metadata is missing."
[ -f "$staged_root/runtime/node-llama-cpp.js" ] || die "Release native runtime is missing."
grep -F "\"version\": \"$version\"" "$staged_root/release.json" >/dev/null ||
  die "Release metadata does not match $version."
if [ "$platform" = "darwin" ] &&
  is_official_repository "$REPOSITORY" &&
  [ -z "${THREADNOTE_RELEASE_SOURCE:-}" ] &&
  [ -z "${THREADNOTE_RELEASE_DOWNLOAD_ROOT:-}" ]; then
  require_command codesign
  require_command file
  find "$staged_root/runtime" -type f -print |
    while IFS= read -r native_file; do
      if file "$native_file" | grep -q 'Mach-O'; then
        verify_code_signature "$native_file"
      fi
    done
  verify_code_signature "$staged_root/threadnote"
fi

write_promotion_journal
fail_after_promotion_step_if_requested journaled
if [ -e "$release_root" ]; then
  mv "$release_root" "$backup_root"
fi
fail_after_promotion_step_if_requested previous-backed-up
if ! mv "$staged_root" "$release_root"; then
  recover_release_promotion
  die "Could not promote Threadnote $version."
fi
fail_after_promotion_step_if_requested release-promoted
rm -rf "$backup_root"
rm -f "$promotion_journal"
staged_root=""
chmod 755 "$release_root/threadnote"
release_installation_lock

say "Installed standalone Threadnote $version"
THREADNOTE_INSTALL_ROOT="$install_root" "$release_root/threadnote" install "$@"

configured_launcher_directory="$(printf '%s' "${THREADNOTE_BIN_DIR:-}" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
if [ -n "$configured_launcher_directory" ]; then
  launcher_directory="$configured_launcher_directory"
  launcher_directory_is_default=false
else
  launcher_directory="$HOME/.local/bin"
  launcher_directory_is_default=true
fi
case "$launcher_directory" in
  '~') launcher_directory="$HOME" ;;
  '~/'*) launcher_directory="$HOME/${launcher_directory#\~/}" ;;
  /*) ;;
  *) launcher_directory="$(pwd -P)/$launcher_directory" ;;
esac
launcher_directory="$(printf '%s\n' "$launcher_directory" | normalize_relative_path)"
launcher_path="$launcher_directory/threadnote"
mcp_launcher_path="$launcher_directory/threadnote-mcp-server"
release_root_physical="$(cd "$release_root" && pwd -P)"
verify_managed_launcher \
  "$launcher_path" \
  cli \
  "$release_root_physical/threadnote" \
  "$temporary_root/expected-threadnote-launcher"
verify_managed_launcher \
  "$mcp_launcher_path" \
  mcp \
  "$release_root_physical/threadnote" \
  "$temporary_root/expected-threadnote-mcp-launcher"
if [ "$launcher_directory_is_default" = true ]; then
  configure_default_command_path
fi
command_display="$(shell_quote "$launcher_path")"

say ""
say "Threadnote is installed. Next:"
say "  $command_display doctor --dry-run"
say "  $command_display mcp-install codex --apply    # if you use Codex"
say "  $command_display mcp-install claude --apply   # if you use Claude"
say "  $command_display mcp-install cursor --apply   # if you use Cursor"
