const CLI_SUBCOMMANDS = {
  cloud: ['cursor'],
  context: ['brief'],
  graph: [
    'analyze',
    'communities',
    'community',
    'compact',
    'confidence',
    'diagnostics',
    'explain',
    'export',
    'groups',
    'hubs',
    'impact',
    'index',
    'inventory',
    'neighbors',
    'node',
    'path',
    'publisher',
    'purge',
    'query',
    'remove-view',
    'repair',
    'report',
    'share',
    'stats',
    'status',
    'surprises',
    'topology',
    'watch',
  ],
  inbox: ['scan'],
  index: ['purge', 'rebuild', 'status', 'verify'],
  jev: ['status'],
  'local-ai': ['disable', 'enable', 'install', 'model', 'start', 'status', 'stop', 'uninstall'],
  models: ['install', 'list', 'remove', 'runtime', 'select', 'verify'],
  projection: ['add', 'list', 'publish', 'remove', 'status', 'sync'],
  share: [
    'conflict',
    'conflicts',
    'init',
    'install-artifacts',
    'list',
    'publish',
    'publish-artifact',
    'publish-bundle',
    'remove',
    'rename',
    'set-access',
    'set-url',
    'status',
    'sync',
    'unpublish',
  ],
  source: ['add', 'inventory', 'list', 'remove', 'status', 'sync'],
  slack: ['probe'],
  workset: ['list', 'prepare', 'show', 'status'],
} as const;

const CLI_TOP_LEVEL_OPERATIONS = [
  'archive',
  'auto-update-worker',
  'cloud',
  'compact',
  'codex-resume-hook',
  'context',
  'doctor',
  'enrich-memories',
  'export-pack',
  'finalize-code-refs',
  'forget',
  'graph',
  'handoff',
  'image-projection',
  'import-pack',
  'inbox',
  'index',
  'init-manifest',
  'install',
  'install-hooks',
  'jev',
  'list',
  'local-ai',
  'logs',
  'manage',
  'mcp-install',
  'migrate',
  'migrate-lifecycle',
  'migrate-memories',
  'migrate-project-names',
  'migrate-projects',
  'models',
  'open',
  'post-update',
  'pre-compact-hook',
  'processes',
  'projection',
  'read',
  'recall',
  'remember',
  'repair',
  'report-issue',
  'seed',
  'seed-skills',
  'session-start-hook',
  'share',
  'source',
  'start',
  'stop',
  'uninstall',
  'update',
  'version',
  'workset',
] as const;

const FIXED_RUNTIME_OPERATIONS = [
  'add_resource',
  'analyze_code_graph',
  'apply_memory_candidates',
  'archive_context',
  'complete_cursor_attestation',
  'compact_context',
  'context_brief',
  'cursor_cloud_status',
  'finalize_code_refs',
  'forget',
  'glob',
  'graph-build',
  'graph-maintenance',
  'graph-query',
  'graph-refresh',
  'health',
  'grep',
  'inspect-code-graph',
  'inspect_code_graph',
  'install_shared_skill',
  'list_context',
  'list_shared_skills',
  'mcp-broker',
  'mcp-broker.child.exit',
  'mcp-broker.child.spawn',
  'mcp-broker.child.write',
  'mcp-broker.promotion.protocol',
  'mcp-broker.promotion.timeout',
  'mcp-broker.unknown',
  'mcp-server',
  'obsidian_publish',
  'read_context',
  'recall-context',
  'recall_context',
  'recall_feedback',
  'remember_context',
  'resource-read',
  'review_session_context',
  'share_bundle',
  'share_conflict_resolve',
  'share_conflict_show',
  'share_conflicts',
  'share_publish',
  'share_skill',
  'search',
  'store',
  'threadnote_guide',
] as const;

const NESTED_CLI_OPERATIONS = Object.entries(CLI_SUBCOMMANDS).flatMap(([topLevel, subcommands]) =>
  subcommands.map(subcommand => `${topLevel}.${subcommand}`),
);

const ANONYMOUS_TELEMETRY_OPERATIONS = new Set<string>([
  ...CLI_TOP_LEVEL_OPERATIONS,
  ...NESTED_CLI_OPERATIONS,
  ...FIXED_RUNTIME_OPERATIONS,
  'cloud.cursor.attest',
  'cloud.cursor.bootstrap',
  'cloud.cursor.config',
  'cloud.cursor.verify',
  'graph.publisher.bootstrap',
  'graph.publisher.serve',
  'graph.publisher.status',
  'graph.share.init',
  'graph.share.join',
  'graph.share.leave',
  'graph.share.status',
  'local-ai.model.switch',
  'share.conflict.resolve',
  'share.conflict.show',
]);

/** Resolve only registered command words; positionals and option values are never appended. */
export function cliAnonymousTelemetryOperation(
  topLevel: string,
  subcommand: string | undefined,
  nestedSubcommand: string | undefined,
): string {
  const knownSubcommands = Object.entries(CLI_SUBCOMMANDS).find(([name]) => name === topLevel)?.[1];
  if (
    knownSubcommands === undefined ||
    subcommand === undefined ||
    !knownSubcommands.some(value => value === subcommand)
  ) {
    return safeAnonymousTelemetryOperation(topLevel);
  }
  const nested = `${topLevel}.${subcommand}.${nestedSubcommand ?? ''}`;
  if (ANONYMOUS_TELEMETRY_OPERATIONS.has(nested)) return nested;
  return safeAnonymousTelemetryOperation(`${topLevel}.${subcommand}`);
}

/** Final outbound operation allowlist. */
export function safeAnonymousTelemetryOperation(value: string): string {
  return ANONYMOUS_TELEMETRY_OPERATIONS.has(value) ? value : 'unknown';
}
